// Generated by gencpp from file cheetah_msgs/ArmState.msg
// DO NOT EDIT!


#ifndef CHEETAH_MSGS_MESSAGE_ARMSTATE_H
#define CHEETAH_MSGS_MESSAGE_ARMSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Quaternion.h>

namespace cheetah_msgs
{
template <class ContainerAllocator>
struct ArmState_
{
  typedef ArmState_<ContainerAllocator> Type;

  ArmState_()
    : header()
    , arm_pos()
    , arm_vel()
    , arm_force()
    , arm_ori()  {
    }
  ArmState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , arm_pos(_alloc)
    , arm_vel(_alloc)
    , arm_force(_alloc)
    , arm_ori(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _arm_pos_type;
  _arm_pos_type arm_pos;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _arm_vel_type;
  _arm_vel_type arm_vel;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _arm_force_type;
  _arm_force_type arm_force;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _arm_ori_type;
  _arm_ori_type arm_ori;





  typedef boost::shared_ptr< ::cheetah_msgs::ArmState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cheetah_msgs::ArmState_<ContainerAllocator> const> ConstPtr;

}; // struct ArmState_

typedef ::cheetah_msgs::ArmState_<std::allocator<void> > ArmState;

typedef boost::shared_ptr< ::cheetah_msgs::ArmState > ArmStatePtr;
typedef boost::shared_ptr< ::cheetah_msgs::ArmState const> ArmStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cheetah_msgs::ArmState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cheetah_msgs::ArmState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cheetah_msgs::ArmState_<ContainerAllocator1> & lhs, const ::cheetah_msgs::ArmState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.arm_pos == rhs.arm_pos &&
    lhs.arm_vel == rhs.arm_vel &&
    lhs.arm_force == rhs.arm_force &&
    lhs.arm_ori == rhs.arm_ori;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cheetah_msgs::ArmState_<ContainerAllocator1> & lhs, const ::cheetah_msgs::ArmState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cheetah_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cheetah_msgs::ArmState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cheetah_msgs::ArmState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cheetah_msgs::ArmState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cheetah_msgs::ArmState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cheetah_msgs::ArmState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cheetah_msgs::ArmState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cheetah_msgs::ArmState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "93bd95c8a69efe99654876d76d315799";
  }

  static const char* value(const ::cheetah_msgs::ArmState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x93bd95c8a69efe99ULL;
  static const uint64_t static_value2 = 0x654876d76d315799ULL;
};

template<class ContainerAllocator>
struct DataType< ::cheetah_msgs::ArmState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cheetah_msgs/ArmState";
  }

  static const char* value(const ::cheetah_msgs::ArmState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cheetah_msgs::ArmState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point arm_pos\n"
"geometry_msgs/Vector3 arm_vel\n"
"geometry_msgs/Vector3 arm_force\n"
"geometry_msgs/Quaternion arm_ori\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::cheetah_msgs::ArmState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cheetah_msgs::ArmState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.arm_pos);
      stream.next(m.arm_vel);
      stream.next(m.arm_force);
      stream.next(m.arm_ori);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cheetah_msgs::ArmState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cheetah_msgs::ArmState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "arm_pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.arm_pos);
    s << indent << "arm_vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.arm_vel);
    s << indent << "arm_force: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.arm_force);
    s << indent << "arm_ori: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.arm_ori);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHEETAH_MSGS_MESSAGE_ARMSTATE_H
