// Generated by gencpp from file cheetah_msgs/LegsState.msg
// DO NOT EDIT!


#ifndef CHEETAH_MSGS_MESSAGE_LEGSSTATE_H
#define CHEETAH_MSGS_MESSAGE_LEGSSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace cheetah_msgs
{
template <class ContainerAllocator>
struct LegsState_
{
  typedef LegsState_<ContainerAllocator> Type;

  LegsState_()
    : header()
    , foot_pos()
    , foot_vel()
    , foot_force()  {
    }
  LegsState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , foot_pos()
    , foot_vel()
    , foot_force()  {
  (void)_alloc;
      foot_pos.assign( ::geometry_msgs::Point_<ContainerAllocator> (_alloc));

      foot_vel.assign( ::geometry_msgs::Vector3_<ContainerAllocator> (_alloc));

      foot_force.assign( ::geometry_msgs::Vector3_<ContainerAllocator> (_alloc));
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array< ::geometry_msgs::Point_<ContainerAllocator> , 4>  _foot_pos_type;
  _foot_pos_type foot_pos;

   typedef boost::array< ::geometry_msgs::Vector3_<ContainerAllocator> , 4>  _foot_vel_type;
  _foot_vel_type foot_vel;

   typedef boost::array< ::geometry_msgs::Vector3_<ContainerAllocator> , 4>  _foot_force_type;
  _foot_force_type foot_force;





  typedef boost::shared_ptr< ::cheetah_msgs::LegsState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cheetah_msgs::LegsState_<ContainerAllocator> const> ConstPtr;

}; // struct LegsState_

typedef ::cheetah_msgs::LegsState_<std::allocator<void> > LegsState;

typedef boost::shared_ptr< ::cheetah_msgs::LegsState > LegsStatePtr;
typedef boost::shared_ptr< ::cheetah_msgs::LegsState const> LegsStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cheetah_msgs::LegsState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cheetah_msgs::LegsState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cheetah_msgs::LegsState_<ContainerAllocator1> & lhs, const ::cheetah_msgs::LegsState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.foot_pos == rhs.foot_pos &&
    lhs.foot_vel == rhs.foot_vel &&
    lhs.foot_force == rhs.foot_force;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cheetah_msgs::LegsState_<ContainerAllocator1> & lhs, const ::cheetah_msgs::LegsState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cheetah_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cheetah_msgs::LegsState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cheetah_msgs::LegsState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cheetah_msgs::LegsState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cheetah_msgs::LegsState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cheetah_msgs::LegsState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cheetah_msgs::LegsState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cheetah_msgs::LegsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75ade754aa154ddc0a853e04f28fa0f5";
  }

  static const char* value(const ::cheetah_msgs::LegsState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75ade754aa154ddcULL;
  static const uint64_t static_value2 = 0x0a853e04f28fa0f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::cheetah_msgs::LegsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cheetah_msgs/LegsState";
  }

  static const char* value(const ::cheetah_msgs::LegsState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cheetah_msgs::LegsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point[4] foot_pos\n"
"geometry_msgs/Vector3[4] foot_vel\n"
"geometry_msgs/Vector3[4] foot_force\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::cheetah_msgs::LegsState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cheetah_msgs::LegsState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.foot_pos);
      stream.next(m.foot_vel);
      stream.next(m.foot_force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegsState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cheetah_msgs::LegsState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cheetah_msgs::LegsState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "foot_pos[]" << std::endl;
    for (size_t i = 0; i < v.foot_pos.size(); ++i)
    {
      s << indent << "  foot_pos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.foot_pos[i]);
    }
    s << indent << "foot_vel[]" << std::endl;
    for (size_t i = 0; i < v.foot_vel.size(); ++i)
    {
      s << indent << "  foot_vel[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.foot_vel[i]);
    }
    s << indent << "foot_force[]" << std::endl;
    for (size_t i = 0; i < v.foot_force.size(); ++i)
    {
      s << indent << "  foot_force[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.foot_force[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHEETAH_MSGS_MESSAGE_LEGSSTATE_H
